config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"

  get "sign_in", to: "sessions#new"
  get "sign_up", to: "users#new"
  delete "sign_out", to: "sessions#destroy"

  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  resources :users, param: :hashid, only: %i[index show create] do
    scope module: :users do
      resource :setting, only: %i[show edit update]
    end
  end
  resources :posts, param: :hashid

  namespace :developments do
    resources :sessions, only: %i[create]
  end
end

app/views/layouts/_content_head.html.erb
<link rel="stylesheet" href="<%= prism_theme_css %>" integrity="sha512-naBrNzTEplW1xpCmrireVtPafiVBwOwFTVhvxH5zspfRL9QeZsaPuPxJZKnSFrFCcFF6XkoT6AiYsN+9dUuo2Q==" crossorigin="anonymous" referrerpolicy="no-referrer">
<script src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.26.0/prism.min.js" data-manual integrity="sha512-pSVqGtpGygQlhN8ZTHXx1kqkjQr30eM+S6OoSzhHGTjh6DKdfy7WZlo1DNO9bhtM0Imf6xNLznZ7iVC2YUMwJQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.26.0/plugins/autoloader/prism-autoloader.min.js" integrity="sha512-GP4x8UWxWyh4BMbyJGOGneiTbkrWEF5izsVJByzVLodP8CuJH/n936+yQDMJJrOPUHLgyPbLiGw2rXmdvGdXHA==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>

app/views/layouts/_footer.html.erb
<div class="flex justify-center items-center gap-1 mt-8">
  <div>&copy;</div>
  <div>2022</div>
  <div>
    <%= link_to "@sijiaoh", "https://twitter.com/sijiaoh", {
          class: "text-sky-400",
          target: "_blank",
          rel: "noopener noreferrer"
        } %>
  </div>
</div>

app/views/layouts/_google_analytics.html.erb
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=<%= ga_measurement_id %>"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', '<%= ga_measurement_id %>', {
    send_page_view: false,
    <%= "debug_mode: true," unless ga_measurement_id.start_with? "G-" %>
  });
</script>

app/views/layouts/_header.html.erb
<header class="horizontal-center justify-between">
  <div>
    <%= link_base t("title"), root_url %>
  </div>
  <div class="horizontal">
    <% if user.present? %>
      <%= link_primary Users::Setting.model_name.human, user_setting_path(current_user) %>
      <%= button_primary t("sign_out"), sign_out_path, method: :delete %>
    <% else %>
      <%= link_primary t("sessions.new.title"), sign_in_path %>
    <% end %>
  </div>
</header>

app/views/layouts/_messages.html.erb
<div>
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice">
      <%= notice %>
    </p>
  <% end %>
  <% if alert.present? %>
    <p class="py-2 px-3 bg-red-50 mb-5 text-red-500 font-medium rounded-lg inline-block" id="alert">
      <%= alert %>
    </p>
  <% end %>
</div>

app/views/layouts/_wysiwyg_head.html.erb
<script src="https://cdnjs.cloudflare.com/ajax/libs/tinymce/5.10.2/tinymce.min.js" integrity="sha512-MbhLUiUv8Qel+cWFyUG0fMC8/g9r+GULWRZ0axljv3hJhU6/0B3NoL6xvnJPTYZzNqCQU3+TzRVxhkE531CLKg==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= display_meta_tags site: t("title") %>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <% if ga_measurement_id.present? %>
      <%= render "layouts/google_analytics" %>
    <% end %>

    <%= render "layouts/wysiwyg_head" %>
    <%= render "layouts/content_head" %>
  </head>

  <body>
    <%= render "layouts/header", user: current_user %>
    <main class="container mx-auto px-6">
      <%= render "layouts/messages" %>
      <%= yield %>
    </main>
  </body>
</html>